services:
  postgres:
    image: postgres:latest
    container_name: postgres_luodingo
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    restart: always 
    networks:
      luodingo_network:
        ipv4_address: "192.168.93.20"
    volumes:
      - ./pgdata:/var/lib/postgresql/data         
  luodingo:
    #Make sure to change architecture to the one used on your machine
    image: "dafraer/luodingo:3.0-arm64"
    container_name: luodingo
    depends_on:
      - postgres
    environment:
    #Change the environmental variables to your own
      TOKEN: <your_telegram_bot_token>
      DB_URI: "postgres://postgres:mysecretpassword@postgres:5432/postgres?sslmode=disable"
    restart: always
    networks:
      luodingo_network:
        ipv4_address: "192.168.93.21"
networks:
  luodingo_network:
    ipam: 
      driver: default
      config:
        - subnet: "192.168.93.0/24"
